In [3]:
import numpy as np
from sklearn import mixture
import pandas as pd

In [42]:
X = pd.read_csv('samples_X.txt',header=None)
X = X.values

# X = pd.read_csv('x.txt',header=None)
# X = X.values

In [82]:
bic = []
for n_components in range(1,4):
        # Fit a Gaussian mixture with EM
        gmm = mixture.GaussianMixture(n_components=n_components,
                                      covariance_type='full')
        gmm.fit(X)
        bic.append(gmm.bic(X))
bic

[3262.4629511689423, 2935.830132657097, 2784.924980996709]

In [74]:
gmm.score_samples(X)

array([ -5.08115765,  -5.31306787,  -4.05577797,  -5.56776419,
        -4.38948333,  -5.70702887,  -5.69357147,  -4.48724278,
        -4.15817224,  -7.30838605, -10.39180107,  -4.54494415,
        -4.23437243,  -5.04122303,  -7.08927441,  -6.01699195,
        -5.87748041,  -6.86322069,  -3.9272485 ,  -4.82713174,
        -4.17130518,  -4.63179925,  -4.53772043,  -4.89501445,
        -5.23441072,  -3.98015432,  -5.02278076,  -4.74241157,
        -3.89370649,  -6.35177641,  -4.57694384,  -4.46558811,
        -4.02561757,  -6.19956063,  -4.08463578,  -4.13439018,
        -3.87680658,  -3.98030751,  -5.37686077,  -7.82924361,
        -4.32830499,  -4.29892819,  -4.97366961,  -5.95608399,
        -4.13859522,  -4.92664508,  -4.8802109 ,  -5.43398054,
        -4.38328784,  -4.39725141,  -7.18988038,  -5.42596233,
        -4.53248887,  -4.4372905 ,  -5.3444752 ,  -4.10819652,
        -5.58783994,  -6.87450627,  -4.23481171,  -4.24041046,
        -6.99754189,  -4.4744076 ,  -5.3404538 ,  -6.24

In [65]:
gmm.score_samples??

In [61]:
gmm._estimate_weighted_log_prob??

In [60]:
gmm._estimate_log_prob(X)

array([[ -44.12433026,   -4.15956756, -122.6073125 ],
       [ -32.9362773 ,   -4.39515695, -100.56350108],
       [ -54.03328984,   -3.14115295, -135.13444331],
       [ -34.40661207,   -4.65409915, -101.20952776],
       [ -49.59124624,   -3.4762838 , -127.93441576],
       [ -38.93947871,   -4.7859081 , -112.80370816],
       [ -54.71760921,   -4.77594062, -132.83879488],
       [ -57.2426692 ,   -3.57386653, -140.90916717],
       [ -39.5744392 ,   -3.24280687, -112.46109116],
       [ -54.86931989,   -6.3922505 , -139.65515746],
       [ -48.17728077,   -9.48665849, -120.63368441],
       [ -42.04768837,   -3.63029686, -116.59720906],
       [ -37.568028  ,   -3.31116001, -111.45884079],
       [ -62.9045092 ,   -4.12081938, -147.55969034],
       [ -52.32754531,   -6.17829772, -130.71470172],
       [ -65.42586532,   -5.09657607, -150.09144635],
       [ -27.90327018,   -4.93983471,  -94.72499562],
       [ -56.98392928,   -5.95362057, -141.64071943],
       [ -45.62432254,   -3.

In [62]:
gmm._estimate_log_weights??

In [54]:
gmm.weights_

array([0.06081439, 0.04394559, 0.03068595, 0.10007367, 0.02591901,
       0.10125985, 0.02379287, 0.08924972, 0.008     , 0.03524987,
       0.049551  , 0.02391865, 0.04379548, 0.04647267, 0.05707225,
       0.08832315, 0.02595644, 0.1034045 , 0.01199972, 0.03051523])

In [67]:
gmm.bic??

In [68]:
gmm.score(X)

-5.052601199844829

In [83]:
gmm._n_parameters()

29

In [78]:
_, n_features = gmm.means_.shape
cov_params = gmm.n_components * n_features * (n_features + 1) / 2.

In [79]:
cov_params

12.0

In [80]:
n_features

3

In [81]:
gmm.n_components

2